### ISSUE TITLE
Trying to connect to a WPA2 network opens network plug instead of asking for password.

### ISSUE THREAD

**Issue by arshubham** [elementary/wingpanel-indicator-network#101]
OS: juno-beta1
Steps: 
1. Click on a secured network.
2. Instead of asking for password, it opens network plug and that too on Ethernet panel.

So I have to switch to WiFi panel and click on the network and type the password there.

**Comment by AlonsoEnrique** [comment]
Same error here, test Juno beta 1 in live USB.

**Comment by cassidyjames** [comment]
I don't seem to get this consistently, so I'm not sure what's causing it. We should see if we can reliably reproduce it.

**Comment by danrabbit** [comment]
Closing as a duplicate of #32
