### ISSUE TITLE
[i18n]There are a lot of untranslated components of network settings in network.

### ISSUE THREAD

**Issue by bagjunggyu** [elementary/wingpanel-indicator-network#102]
<Wireless connection>
* general - Connection priority for auto-activation
* Proxy - For browser only , PAC script, Import script form a file...
* IPv4 settings - Additional static addresses
* IPv6 settings - Additional static addresses , IPv6 address gegeration mode: , stable privacy

<Ethernet connection>
wireless connection plus
* Ethernet - Link negotitaion, Duplex:
* DCB - Use Data Bridging (DCB) for this connection, Options...

**Comment by tintou** [comment]
Are you sure that this is the right component ?
If so, a screenshot might help to locate it

**Comment by bagjunggyu** [comment]
Here is for one sample.
![2018-07-17 20 22 17](https://user-images.githubusercontent.com/2834031/42814448-352302b4-89ff-11e8-978f-761715216128.png)

**Comment by tintou** [comment]
Unfortunately this is not handled by us but by NetworkManager.
These strings are translatable here https://l10n.gnome.org/module/NetworkManager/

Closing it as it does not affect the indicator
