### ISSUE TITLE
Max line length is not strictly followed -- what is the hard limit?

### ISSUE THREAD

**Issue by skewty** [elementary/wingpanel-indicator-network#109]
https://github.com/elementary/wingpanel-indicator-network/blob/d8ae0885cce5766c2389d2f73880cb1cde9803cf/.editorconfig#L11

I am looking into adding multiple vlan and vpn support and was surprised to see that this line length is not stricly followed (perhaps loosely at best).  Is there a hard limit?

**Comment by cassidyjames** [comment]
See the elementary code reference at https://elementary.io/docs/code/reference#columns-per-line. If a specific line that you're touching can be refactored over multiple lines, then feel free to do so in your PR.

**Comment by skewty** [comment]
The hard limits don't appear to be very hard as I have seen much longer lines in the 10 minutes since I started looking at the code.

For example:
https://github.com/elementary/wingpanel-indicator-network/blob/d8ae0885cce5766c2389d2f73880cb1cde9803cf/src/Indicator.vala#L69

No big deal..  I don't mean to be a dick about it, but hard limits, if specified, should be followed.

**Comment by cassidyjames** [comment]
@skewty for sure, and no code is perfect. :wink: If it's related to code you're touching feel free to refactor it in that PR. Otherwise it can be refactored in a separate cleanup branch and PR.
