### ISSUE TITLE
from shutdown

### ISSUE THREAD

**Issue by raijinsuan** [elementary/wingpanel-indicator-network#124]
every time I turn ON my laptop,my wifi panel indicators cant turn ON the wifi from its panel indicator, I should go to system settings to turn it ON. 
the HTOP isnt working since the day that I installed my OS.
The GNOME browser wont respond if I open FACEBOOK site, it goes white blank page.

**Comment by peteruithoven** [comment]
You're mentioning 3 issues without any details, this isn't helpful.
As far as I know elementary OS doesn't include options to turn wifi on/off on boot, so I'm afraid you'll have to research how people solved this in Ubuntu.

**Comment by peteruithoven** [comment]
Tips: https://elementary.io/docs/code/reference#reporting-bugs
