### ISSUE TITLE
Not possible turn on wifi after turn off

### ISSUE THREAD

**Issue by garbunus** [elementary/wingpanel-indicator-network#125]
When I turn off wifi using the button on top panel, I can't turn again using this button. To turn on, I need go to configuration and turn on.

Thank you guys for your awesome work. Elementary is the best distro already I used. Falling in love for this

**Comment by garbunus** [comment]
Thank you so much.
![Screen record from 2019-06-19 16 16 18](https://user-images.githubusercontent.com/28625502/59797553-ee81eb00-92ad-11e9-988d-3532f66d3329.gif)

**Comment by janxkoci** [comment]
I have this issue since at least Loki, I don't understand why is it still there. It was also reported countless of times.

The toggle gets grayed out after toggling it off so it cannot be turned on.
