### ISSUE TITLE
Selecting "Connect to Hidden Network" makes a wingpanel icon pop-up on the dock.

### ISSUE THREAD

**Issue by Blast-City** [elementary/wingpanel-indicator-network#129]
1- Click on the Wi-Fi icon.
2- Select "Connect to Hidden Network..."

**Result:** An icon called "Wingpanel" appears on the dock and doesn't disappear when the "connect to hidden network" dialog is canceled.

`killall wingpanel` makes it disappear.

**Comment by ryonakano** [comment]
Related: https://github.com/elementary/wingpanel/issues/52

**Comment by 4jNsY6fCVqZv** [comment]
@ryonakano 
Thank you for linking! So far I was not aware of what action had preceded my observation. I only accidentally try to connect to hidden networks, because the display of the available networks in the wingpanel-indicator-network always jumps back and forth. And with them also the menu items do, like VPN.

I can confirm that it occurs at least by connecting to a hidden network and that `killall wingpanel` or reboot do fix the problem for me.

My question is: What causes the problem and how can this issue be fixed?

**Comment by 4jNsY6fCVqZv** [comment]
@ricotz Why is Plank not a part of https://github.com/elementary? It would be wonderful if you could fix it somehow! Do you have an idea?

**Comment by ryonakano** [comment]
> I can confirm that it occurs at least by connecting to a hidden network and that `killall wingpanel` or reboot do fix the problem for me.
> However, if I connect to a hidden network via switchboard-plug-network, the problem does not occur.

I did also noticed this, so I investigated and compared the applicable codes between Wingpanel Network Indicator and Switchboard Network Plug.

This is the [applicable code](https://github.com/elementary/switchboard-plug-network/blob/3d6553efc9bcff2331f33d1673911073d6fff5ae/src/Views/WifiPage.vala#L567-L578) that handles showing the "Connect to Hidden Network" dialog in Switchboard Network Plug:

```vala
    var hidden_dialog = new NMA.WifiDialog.for_other (network_manager.client);
    hidden_dialog.deletable = false;
    hidden_dialog.transient_for = (Gtk.Window) get_toplevel ();
    hidden_dialog.window_position = Gtk.WindowPosition.CENTER_ON_PARENT;
    hidden_dialog.response.connect ((response) => {
        if (response == Gtk.ResponseType.OK) {
            connect_to_network.begin (hidden_dialog);
        }
    });

    hidden_dialog.run ();
    hidden_dialog.destroy ();
```

And this is the [applicable code](https://github.com/elementary/wingpanel-indicator-network/blob/b67512a7140a9ad9e5fe5363b57a770fe8d21956/src/Widgets/WifiInterface.vala#L122-L172) that handles showing the "Connect to Hidden Network" dialog in Wingpanel Network Indicator:

```vala
    var hidden_dialog = new NMA.WifiDialog.for_other (nm_client);
    hidden_dialog.deletable = false;

    hidden_dialog.response.connect ((response) => {
        // Note: omitted the signal code part because it's too long to show here
    });

    hidden_dialog.run ();
    hidden_dialog.destroy ();
```

The most important difference between these code is, whether they have the line `hidden_dialog.transient_for = (Gtk.Window) get_toplevel ();` or not. And I think not having this line in the Wingpanel Network Indicator code causes the issue; **adding this line to the Wingpanel Network Indicator code fixes the issue.** I'm not sure the actual reason though; I suppose adding this line might allow Plank to recognize the dialog as a child dialog of the currently running Wingpanel instance correctly. 🤔

**Comment by ryonakano** [comment]
I think the worst problem of this issue is that Wingpanel gets minimized and inaccessible when you click the Wingpanel icon in Plank as @4jNsY6fCVqZv mentioned in https://github.com/elementary/wingpanel/issues/52#issuecomment-517419474.
