### ISSUE TITLE
Consider displaying the VPN session before the Wi-Fi connections

### ISSUE THREAD

**Issue by matfantinel** [elementary/wingpanel-indicator-network#139]
I use a VPN daily to connect via RDP to a machine where I do my daily job. Since the VPN belongs to the company I work to, I enable/disable the connection multiple times a day, since I don't want them filtering my network when I'm not working.

However, some frustration comes from the fact that Wi-Fi connections are listed **before** the VPN and the list updates constantly, which may make it's height change. Often I line up the mouse on the VPN connection, and when I click, the list has updated and I select a Wi-Fi network instead.

Here is a recording of the problem:
![Screen record from 2019-10-03 12 32 40](https://user-images.githubusercontent.com/24247035/66141402-002b9c00-e5da-11e9-8d8e-b51c87b4b44c.gif)

I figure that the VPN toggle doesn't appear until you set up a VPN yourself. Just like the Wired toggle, I believe it would make sense for the VPN one to be above the Wireless one. Even if my case may not be that common (I'm not sure if it is), **I believe having toggles below a list that can change height after first load is very error-prone**, and this could be a simple QoL improvement. Considering the VPN list doesn't change dynamically, this could solve an issue.

**Comment by DomHudson** [comment]
Related: https://github.com/elementary/wingpanel-indicator-network/issues/134

**Comment by danrabbit** [comment]
Yeah I agree that it's problematic to display this list below wireless networks. It either needs to come first to avoid the jumping or we need a tabbed interface
