### ISSUE TITLE
Poor WiFi signal

### ISSUE THREAD

**Issue by erikusaj** [elementary/wingpanel-indicator-network#143]
WiFi signal is poor only nearest AP get picked.
Elementary OS shows 2 APs

Compared:
Windows showed 11 APs 
OS X shows 11 APs  
Android Phone 20 APs (including almost no signal)

same issue as other users noticed by others:
https://elementaryos.stackexchange.com/questions/18256/wi-fi-on-elementary-is-such-a-weak-signal

Or just write Elementary OS is intended for advanced users only.

**Comment by andirsun** [comment]
I think this is not an elementary bug, maybe is related to kernel driver for your wifi card. So you can close the issue.

**Comment by cassidyjames** [comment]
Yeah, this is going to depend on the specific hardware and its drivers, and whether or not the hardware manufacturer has provided open source drivers for the kernel—all things outside of our control. We always recommend getting a computer with elementary OS for the best possible experience, or at least purchasing hardware from a company that explicitly supports Linux, and then this issue could be resolved with the hardware manufacturer.
