### ISSUE TITLE
rtl8812au-dkms driver stopped working after kernel 5.3 update merged

### ISSUE THREAD

**Issue by no-self** [elementary/wingpanel-indicator-network#146]
rtl8812au-dkms driver stopped working after kernel 5.3 update merged
after fresh install still not working

**Comment by danrabbit** [comment]
elementary doesn't ship Linux 5.3. We recommend sticking to the provided LTS kernel maintained by Canonical.

Installing an unsupported kernel can indeed have adverse effects. Closing since unsupported components are in use

**Comment by danrabbit** [comment]
Oops, my bad. I didn't realize that Ubuntu has updated to 5.3 as of yesterday!

In that case, issues with the HWE kernel are tracked in Launchpad here: https://launchpad.net/ubuntu/+source/linux-meta-hwe/+bugs
