### ISSUE TITLE
vpn add l2tp have a error,not connector

### ISSUE THREAD

**Issue by Timetry** [elementary/wingpanel-indicator-network#155]
(nm-applet:6437): Gtk-CRITICAL **: 21:36:59.898: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed

(nm-applet:6437): Gtk-CRITICAL **: 21:36:59.898: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed

(nm-applet:6437): Gtk-WARNING **: 21:36:59.900: Can't set a parent on widget which has a parent

**Comment by danirabbit** [comment]
This is an old report and it doesn't have clear directions to reproduce. Closing as "Incomplete". Feel free to reopen if you can still reproduce the issue and can provide directions on how
