### ISSUE TITLE
Update screenshot

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/wingpanel-indicator-network#188]
The screenshot still shows WiFi networks with a lock next to each, which is before we switched to the "secure-by-default" way of doing things, so it's definitely out of date.

I don't know how many more stylesheet changes there may be though, so updating the screenshot now may be premature.

**Comment by 4jNsY6fCVqZv** [comment]
This issue can be closed now, right?

**Comment by cassidyjames** [comment]
Fixed in #227
