### ISSUE TITLE
Odin 6: Wingpanel network shows strange vpn connection

### ISSUE THREAD

**Issue by jcamposz** [elementary/wingpanel-indicator-network#195]
Using Odin 6 updated to Nov 21st, Wingpanel network shows an empty vpn connection 
![imagen](https://user-images.githubusercontent.com/11057356/99870106-ab2d5980-2bd0-11eb-8487-4c33564341e0.png)

if you try to remove it , it doesn't exist in vpn panel

![imagen](https://user-images.githubusercontent.com/11057356/99870121-c6986480-2bd0-11eb-8646-5f731bff5e77.png)

**Comment by cassidyjames** [comment]
I cannot reproduce this on any of my hardware or installs here. @fabiozaramella @jcamposz Could you please share some information about your networking hardware or any third-party apps you've installed if you're both able to reproduce this?

**Comment by jcamposz** [comment]
I don't know if this can help you but I attached the network connection panel with my connection list.
![imagen](https://user-images.githubusercontent.com/11057356/100319252-97626880-2fbf-11eb-9cef-8cbce2657dc4.png)

**Comment by jcamposz** [comment]
I've guessed where the problem is , I've resolved in my machine but I don't know if it is the correct solution. All my changes are in VpnInterface:
1. I don't use the blank item :  //vpn_list.add (blank_item); 
2. I've changed  to show_vpn(length>0) in check_vpn_availability

In code:
        vpn_list = new Gtk.ListBox () {
            activate_on_single_click = false,
            visible = true
        };
        //vpn_list.add (blank_item);
And:
    private void check_vpn_availability () {
        var length = vpn_list.get_children ().length ();
        // The first item is the blank item
        show_vpn (length > 0);
    }

**Comment by jcamposz** [comment]
I think I understand the reason of blank radio button, this is because radio button always have one selected. By default you choose this one,  so you can select the vpn you want without connect to a vpn.

**Comment by dr-Styki** [comment]
Hi, same here. Not issue on Hera. Juste add openfortivpn, network-manager-fortisslvpn and network-manager-fortisslvpn-gnome to manage forti vpn.
![Screenshot from 2021-01-11 13-23-09](https://user-images.githubusercontent.com/63053131/104182407-b2265a80-5410-11eb-9293-5efb2e6032fb.png)
![Screenshot from 2021-01-11 13-23-27](https://user-images.githubusercontent.com/63053131/104182425-b5b9e180-5410-11eb-9a71-16e21318580d.png)

**Comment by wout** [comment]
I'm having the same issue:

![image](https://user-images.githubusercontent.com/107324/124459859-8912d100-dd86-11eb-92f0-9ef7c062b30c.png)

![image](https://user-images.githubusercontent.com/107324/124459889-94fe9300-dd86-11eb-98e7-0e66dc62796b.png)

The VPN I've configured is a Cisco VPN, for which I installed the following packages:

```
sudo apt install network-manager-vpnc network-manager-vpnc-gnome
```

There is some strange behaviour as well. If you click the main VPN slider button, it remains active and the VPN slider button is instantly activated again. Then if you click the VPN slider button again, it will turn off.

**Comment by yakleg** [comment]
Hi @cassidyjames,
I've reproduced the bug on my machine.
I also started doing some improvements in the indicator and hope I will provide PR soon.
Shall I assign the issue to myself?

**Comment by jeremypw** [comment]
Is anyone able to confirm whether PR #230 fixes this issue?

**Comment by itoshkov** [comment]
> Is anyone able to confirm whether PR #230 fixes this issue?

It works for me.
