### ISSUE TITLE
Add tooltip to indicator icon

### ISSUE THREAD

**Issue by cassidyjames** [elementary/wingpanel-indicator-network#197]
## Problem

A tooltip could provide some extra information before clicking or just some quicker information that feels faster to access without clicking at all.

## Proposal

Add a tooltip with the status it is indicating, and some other quick info:

>Connected to “Network Name”

I'm not sure, but we could also maybe include connection strength as a percent or “Weak,” “Good,” “Excellent” or something?

## Prior Art

We added a tooltip to Applications Menu with a longer description and keyboard shortcuts.

**Comment by pongloongyeat** [comment]
If that's the case wouldn't it be quite odd to have only tooltips for the network indicator but not the other wingpanel indicators?
