### ISSUE TITLE
Tooltip show 'Connected to (null)'

### ISSUE THREAD

**Issue by andirsun** [elementary/wingpanel-indicator-network#209]
## What Happened

Im connected to wifi network but the tooltip indicator show null as name.

## Expected Behavior

display the name of wifi

![Screenshot from 2021-01-02 10-50-44](https://user-images.githubusercontent.com/22928302/103461025-1b0f2380-4ce9-11eb-8ca9-8e1e1fa63aac.png)

## Platform Information

6.0 Daily build

**Comment by pongloongyeat** [comment]
Works fine for me. Could you provide steps on how to reproduce?

![Screenshot from 2021-01-06 20-52-06](https://user-images.githubusercontent.com/31680656/103770579-353a6000-5061-11eb-875d-1d9b2964855c.png)

**Comment by andirsun** [comment]
> Works fine for me. Could you provide steps on how to reproduce?
> 
> ![Screenshot from 2021-01-06 20-52-06](https://user-images.githubusercontent.com/31680656/103770579-353a6000-5061-11eb-875d-1d9b2964855c.png)

Just occur couple of times at week. Im not able to reproduce the issue, maybe is a hardware related thing but maybe some other people face the same behavior.

**Comment by cassidyjames** [comment]
Thanks for reporting! We'll keep our eyes on this and see if other people can reproduce it. Some information about your Wi-Fi card might be useful as well.

**Comment by andirsun** [comment]
After few months in Odin, Im not longer able to reproduce the same behavior so Im closing the issue.
