### ISSUE TITLE
No secondary tooltip text/middle-click functionality

### ISSUE THREAD

**Issue by pongloongyeat** [elementary/wingpanel-indicator-network#211]
## Problem

Network indicator has no secondary tooltip text since it doesn't have any middle-click functionality, unlike the other system indicators.

## Proposal

1. It should have one for uniformity. Perhaps have middle-click to turn off one of wired or wireless if one of them are on, though I can see this being a problem if the user is connected to both.
2. Another suggestion would perhaps be to separate wired and wireless into separate indicators. This would make it easier to show the user what connection type they are connected to as well. Not sure how viable this is seeing as how #201 is already worked on.

**Comment by danirabbit** [comment]
Fixed in #235
