### ISSUE TITLE
VPN Icon stuck didn't changed when success connected.

### ISSUE THREAD

**Issue by aalfiann** [elementary/wingpanel-indicator-network#212]
## What Happened

VPN Icon stuck didn't changed when success connected.
![Screenshot from 2021-02-13 18-19-39](https://user-images.githubusercontent.com/9458941/107848773-bcc97a80-6e28-11eb-923e-2d0196115c97.png)

## Expected Behavior

VPN Icon must change to success with green color when the VPN connection is successfully connected.

## Platform Information

Elementary OS Hera 5.1.7
Built on Ubuntu 18.04.4 LTS
Linux 4.15.0-112-generic
GTK 3.22.30

**Comment by sempasha** [comment]
https://github.com/elementary/wingpanel-indicator-network/issues/212

Here is [`update` method](https://github.com/elementary/wingpanel-indicator-network/blob/68e58b05a4257b8c0f8c939624439dc654b61057/src/common/Widgets/VpnMenuItem.vala#L100-L117). Method when [connection changed](https://github.com/elementary/wingpanel-indicator-network/blob/68e58b05a4257b8c0f8c939624439dc654b61057/src/common/Widgets/VpnMenuItem.vala#L47), on [change of `notify["vpn_state"]`](https://github.com/elementary/wingpanel-indicator-network/blob/68e58b05a4257b8c0f8c939624439dc654b61057/src/common/Widgets/VpnMenuItem.vala#L81), on [radio button toggle](https://github.com/elementary/wingpanel-indicator-network/blob/68e58b05a4257b8c0f8c939624439dc654b61057/src/common/Widgets/VpnMenuItem.vala#L82) and right after [item initialization](https://github.com/elementary/wingpanel-indicator-network/blob/68e58b05a4257b8c0f8c939624439dc654b61057/src/common/Widgets/VpnMenuItem.vala#L89).

```vala
    private void update () {
        label.label = connection.get_id ();
        hide_item (error_img);
        hide_item (spinner);

        switch (vpn_state) {
            case State.FAILED_VPN:
                show_item (error_img);
                break;
            case State.CONNECTING_VPN:
                show_item (spinner);
                if (!radio_button.active) {
                    critical ("An VPN is being connected but not active.");
                }
                check_vpn_connectivity.begin ();
                break;
        }
    }
```

As we can see `update` method modifies item view depending on `vpn_state` which is type of [`Network.State`](https://github.com/elementary/wingpanel-indicator-network/blob/68e58b05a4257b8c0f8c939624439dc654b61057/src/common/Widgets/VpnMenuItem.vala#L22). Behavior defined for two of `vpn_state` possible values (`FAILED_VPN` and `CONNECTING_VPN`), while `Network.State` is a enum with [many other possible values](https://github.com/elementary/wingpanel-indicator-network/blob/e04bfa7b082adeb3fd23e6d22a4de97eb1e78835/src/Utils.vala#L19-L42).

When connection state is `FAILED_VPN` error will be shown, when state is `CONNECTING_VPN` spinner will be shown and [`check_vpn_connectivity`](https://github.com/elementary/wingpanel-indicator-network/blob/68e58b05a4257b8c0f8c939624439dc654b61057/src/common/Widgets/VpnMenuItem.vala#L145-L159) begins.

```vala
    private async void check_vpn_connectivity () {
        if (!checking_vpn_connectivity) {

            checking_vpn_connectivity = true;

            for (int i = 0; i < 20; i++) {
                if (vpn_state == State.CONNECTED_VPN) {
                    hide_item (spinner);
                    checking_vpn_connectivity = false;
                    return;
                }
                yield nap (500);
            }
        }
    }
```

`check_vpn_connectivity` will hide spinner if connection will be in `CONNECTED_VPN`, there will be 20 attempts to do it with interval of 500 ms between attempts.

Here are questions:

  1. Why `check_vpn_connectivity` hides spinner when `vpn_state` is `CONNECTED_VPN` only, what about connection failure and so on?
  2. What is the way `vpn_state` may be changed?
