### ISSUE TITLE
Unable to install libwingpanel-dev dependency

### ISSUE THREAD

**Issue by sempasha** [elementary/wingpanel-indicator-network#215]
Unable to install dependencies because libwingpanel-dev not found. Seems this is related with #214.

## What Happened

```
$ sudo apt install gobject-introspection libgranite-dev libnm-dev libnma-dev libwingpanel-dev meson valac

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libwingpanel-dev
```

## Expected Behavior

All packages to be found and installed.

## Platform Information

Elementary OS 5.1.7 Hera

```
$ uname -a
Linux user 5.4.0-65-generic #73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by davidmhewitt** [comment]
At this stage, most components are targeting the currently unreleased elementary OS 6.0, where `libwingpanel-dev` is available and is the correct package name.

If you wish to compile this on Hera, you will need to install `libwingpanel-2.0-dev` and possible compile an older commit of the indicator depending on whether any Wingpanel 3.0 API features have been used.

**Comment by sempasha** [comment]
Got it. Thank you.
