### ISSUE TITLE
Request: Integrate VPN app connection into wifi indicator

### ISSUE THREAD

**Issue by theuser18** [elementary/wingpanel-indicator-network#233]
## Problem
Currently, using a VPN app means you have to open the app to ensure the VPN is still connected. Currently, I have to resort to enabling app indicators to see the status of my VPN app.

## Proposal
When connected to a VPN app, make the WiFi icon have a colored lock next to it that changes based on VPN connection status.

## Prior Art
Something like [this](https://photos.gograph.com/thumbs/CSP/CSP818/wifi-connection-signal-icon-with-vpn-vector-clipart_k56341126.jpg), but will a colored padlock instead of "VPN."

**Comment by sempasha** [comment]
@theuser18 did you meant something like this 
![Screenshot from 2022-03-03 20-47-00](https://user-images.githubusercontent.com/1610465/156622124-c36092a3-f0aa-4a50-94c2-cf350a99c20a.png)
This is how WiFi indicator behaves right now.

**Comment by peteruithoven** [comment]
That icon with lock doesn't however appear when using applications like [Mozilla VPN](https://www.mozilla.org/en-US/products/vpn/) or [NordVPN's cli](https://github.com/elementary/wingpanel-indicator-network/issues/233). Is the software from these vpn companies maybe doing something wrong where the OS can't notice this is happening? 

Mozilla VPN's client is [opensource and available on Github](https://github.com/mozilla-mobile/mozilla-vpn-client), so we could easily open an issue.

**Comment by danirabbit** [comment]
The network indicator can only support VPNs which use NetworkManager, so if you connect to Nord through System Settings using an OpenVPN config file (for example) it will show up in the indicator.

Closing as "Out of scope" since we can't know about or support VPNs that don't use NetworkManager and we already show an indicator for ones that do
