### ISSUE TITLE
Airplane mode button does not work after "Fix set_property deprecations"

### ISSUE THREAD

**Issue by bobby285271** [elementary/wingpanel-indicator-network#283]
### What Happened?

![](https://user-images.githubusercontent.com/20080233/222042579-e70aaf73-bada-4b61-93ca-69a31b5ede38.png)

The above button does not work for me.

- libnma 1.10.6
- networkmanager 1.40.12

```
PopoverWidget.vala:96: Error setting airplane mode: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: No such property “Enable”
```

Reverting https://github.com/elementary/wingpanel-indicator-network/commit/5ffeb69379369ed57c084485296189b78b70e6c7 fixes the issue.

### Steps to Reproduce

1. Click the airplane mode button.
2. Try to Surf the Internet.

### Expected Behavior

The button does the same thing as the one in switchboard-plug-network.

### OS Version

Other Linux

### Software Version

Compiled from git

**Comment by fayjie92** [comment]
This is also reproducible in elementary OS 7 (updated to latest versions). 
![Screenshot from 2023-03-01 14 09 12](https://user-images.githubusercontent.com/32283602/222148309-f7366969-b70e-43b7-b14e-8c54f2a97fef.png)

Also, there's a click issue with the surroundings of the switch. The VPN also got a serious issue.

Can we revert back to the previous way of doing this @danirabbit until this is fixed?

**Comment by danirabbit** [comment]
@fayjie92 please file separate issue reports for individual issues. It's not possible to properly track unrelated issues as comments
