### ISSUE TITLE
Confusing color issue in the airplane switch icon

### ISSUE THREAD

**Issue by fayjie92** [elementary/wingpanel-indicator-network#291]
### What Happened?

Clicking the 'airplane mode' switch works as expected. But the color stays active even after airplane mode is turned off.
![Screenshot from 2023-03-02 09 12 00](https://user-images.githubusercontent.com/32283602/222370417-1a23e2ce-f263-435f-a98b-a2f58b8a845b.png)

- Here the switch is clicked to deactivate the airplane mode. The color (blue) remained same which is visually confusing. Expected it to be gray. 

### Steps to Reproduce

1. Click the airplane mode switch to activate airplane mode.
2. Click again to deactivate airplane mode.

### Expected Behavior

Expect the color of the switch to be gray when deactivated airplane mode.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
Probably related to #256, or at least fixing this issue would probably resolve both issues
