### ISSUE TITLE
add new wifi network directly from indicator

### ISSUE THREAD

**Issue by snowparrot** [elementary/wingpanel-indicator-network#32]
It is not possible to add a wifi network directly from the indicator.
Instead you have to go inside system settings and type the password there. Very long way.

expected behaviour:
click on password protected wifi in the indicator leads to dialog where you can type the password.

**Comment by danrabbit** [comment]
This functionality is already present. Are you running a fully updated installation of Loki?

**Comment by snowparrot** [comment]
Yes. I am testing now again and still see unexpected behaviour.
Any information I might provide for bug hunting?

**Comment by Philip-Scott** [comment]
@danrabbit Actually. i can confirm. Clicking on a new protected network opens Switchboard on the Networking plug (and you still have to select the new network) instead of requesting the password right away

**Comment by janxkoci** [comment]
I noticed this happens only with some new networks but not with all of them. For some networks the password prompt appears as expected.
