### ISSUE TITLE
  Yesterday, after installing the update pushed by elementaryOS 8, my Ethernet stopped working.

### ISSUE THREAD

**Issue by Yakumo-Yukari** [elementary/wingpanel-indicator-network#320]
### What Happened?

  Yesterday, after installing the update pushed by elementaryOS 8, my Ethernet stopped working.

### Steps to Reproduce

After updating the system, the Ethernet disappeared and the network is unusable.

### Expected Behavior

After updating the system, the Ethernet disappeared and the network is unusable.

### OS Version

8.x (Circe)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

**Comment by ryonakano** [comment]
Duplicate of https://github.com/elementary/switchboard-plug-network/issues/423
