### ISSUE TITLE
Unsecured wireless icon

### ISSUE THREAD

**Issue by ovdeathiam** [elementary/wingpanel-indicator-network#53]
Since the introduction of **Secured-by-default UX** the wingpanel's wireless icon for unsecured network has a lock icon.

![zrzut ekranu z 2017-10-04 07 32 06](https://user-images.githubusercontent.com/946846/31161729-673b2572-a8d9-11e7-9fe3-fc83ef8555c3.png)

I'd suggest that it should be an open lock, a slashed lock.

**Comment by tintou** [comment]
The lock is here when your VPN is enabled
