### ISSUE TITLE
Indicator Network Have Arrow Up And Arrow Down

### ISSUE THREAD

**Issue by torikulhabib** [elementary/wingpanel-indicator-network#68]
Indicator Network Have Arrow Up And Arrow Down Like Smartphone Android OS
![screenshot_2018-02-16-15-29-46](https://user-images.githubusercontent.com/26135527/36299266-cd5c2120-132e-11e8-94cb-0ae828eba9cd.jpg)

**Comment by danrabbit** [comment]
Hey OP can you provide a little more information? Is this a feature request? If so, can you more fully describe the functionality here that you're expecting? What new information is being conveyed?

Closing this report as "Incomplete" for now. Please reopen with more information :)
