### ISSUE TITLE
Indicator doesn't not show available Wi-Fi [$50]

### ISSUE THREAD

**Issue by Djaler** [elementary/wingpanel-indicator-network#70]
While I not open Switchboard Networking Plug, it shows only my active Wi-Fi. You can see it in action by the link https://youtu.be/dGLUQ2Vmy2A. I'm on Juno. Also, I think it can be related to https://github.com/elementary/wingpanel-indicator-network/issues/69

---
There is a bounty on this issue in [Bountysource](https://www.bountysource.com/issues/56042558-indicator-doesn-t-not-show-available-wi-fi)

**Comment by danrabbit** [comment]
I think this might be fixed in master. Can you confirm that this is still happening after updating everything?

**Comment by Djaler** [comment]
Yes, this is still happening to me with all updates
