### ISSUE TITLE
turn on ethernet in wingpanel not working

### ISSUE THREAD

**Issue by torikulhabib** [elementary/wingpanel-indicator-network#71]
turn on ethernet in wingpanel not working

![ethernet](https://user-images.githubusercontent.com/26135527/37473601-10a6b56c-28a1-11e8-8fdb-5c534d8966c3.gif)

**Comment by Djaler** [comment]
I can confirm this.

**Comment by torikulhabib** [comment]
@Djaler  do you look at the notification.
the ethernet symbol not show please fix it too
