### ISSUE TITLE
Indication of VPN connection process

### ISSUE THREAD

**Issue by Djaler** [elementary/wingpanel-indicator-network#93]
Preloader that indicates process of connecting to VPN continues to spin even after connecting
![2018-05-02 00 22 59](https://user-images.githubusercontent.com/7964583/39494478-398f1cda-4d9f-11e8-97a2-8a917e51a2b0.png)

**Comment by carniz** [comment]
Still seeing this in Juno:

![Screenshot from 2019-06-03 09 47 06@2x](https://user-images.githubusercontent.com/1648530/58785183-4e597000-85e5-11e9-8255-6a6a12ccad77.png)

**Comment by 4jNsY6fCVqZv** [comment]
The issue is still relevant. Any idea how to solve this elegantly?
The VPN connection spinner never stands still.

**Comment by queeup** [comment]
Same here. Spinning forever.

**Comment by rafiibrahim8** [comment]
**Still spining in Hera.**

![Screenshot from 2020-05-17 14-47-27](https://user-images.githubusercontent.com/30957188/82139931-9781ee80-984d-11ea-9eb9-7b3e02d88a3c.png)
